language: node_js
sudo: false
node_js:
  - "0.12"
  - "4.0"
before_script:
  - npm install -g istanbul standard jsinspect
script: "npm test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
